services:
  - type: web
    name: agente-rag
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: HF_TOKEN
        sync: false

